/**
 * Stock search queries generated by the script writer
 * (backend/services/clipperAi.js).
 *
 * A stock library cannot search for an idea, only for a thing someone pointed a
 * camera at. Ask it for "determination" and it returns a stranger looking
 * thoughtfully out of a window - and that failure is silent, because an
 * abstract query returns plenty of results and nothing downstream can tell they
 * are all wrong. A measured render came back with seven shots, none of them
 * aviation and several of them exactly that.
 *
 * The prompt asks for concrete nouns. This is the backstop for when it does not
 * get them.
 */

const { constrainQuery, FALLBACK_QUERIES } = require('../../services/clipperAi');

describe('constrainQuery', () => {
  it('leaves a concrete query alone', () => {
    expect(constrainQuery('fighter jet taking off runway')).toBe('fighter jet taking off runway');
    expect(constrainQuery('air traffic control radar screen')).toBe('air traffic control radar screen');
  });

  it('replaces a query with nothing filmable in it', () => {
    expect(FALLBACK_QUERIES).toContain(constrainQuery('determination and focus'));
    expect(FALLBACK_QUERIES).toContain(constrainQuery('making a difficult decision'));
    expect(FALLBACK_QUERIES).toContain(constrainQuery('mental pressure'));
  });

  // Generic people are the same filler by another route: a stock library reads
  // "young candidate" as "stock photo of a human".
  it('treats generic people as unfilmable', () => {
    expect(FALLBACK_QUERIES).toContain(constrainQuery('young candidate making a decision'));
    expect(FALLBACK_QUERIES).toContain(constrainQuery('person thinking under pressure'));
  });

  it('keeps the filmable part of a half-abstract query', () => {
    expect(constrainQuery('stressed person at a desk')).toBe('desk');
    expect(constrainQuery('determined pilot in a cockpit')).toBe('pilot in a cockpit');
  });

  // Stripping leaves dangling function words at both ends, and they only
  // dilute the search.
  it('trims the connective words stripping leaves behind', () => {
    expect(constrainQuery('cockpit view of')).toBe('cockpit view');
    expect(constrainQuery('the radar screen')).toBe('radar screen');
  });

  it('handles an empty or missing query', () => {
    for (const q of ['', null, undefined, '   ']) {
      expect(FALLBACK_QUERIES).toContain(constrainQuery(q));
    }
  });

  // A script whose queries all collapse would otherwise search for the same
  // thing on every beat, and the video would be one clip six times.
  it('varies the fallback by beat so a collapsed script is not one clip', () => {
    const picked = [0, 1, 2, 3].map(i => constrainQuery('success', i));
    expect(new Set(picked).size).toBe(4);
  });

  it('wraps round rather than running out of fallbacks', () => {
    expect(constrainQuery('success', FALLBACK_QUERIES.length)).toBe(FALLBACK_QUERIES[0]);
  });

  // Every fallback has to survive its own rule, or the backstop would hand back
  // something the backstop rejects.
  it('has fallbacks that are themselves concrete', () => {
    for (const q of FALLBACK_QUERIES) expect(constrainQuery(q)).toBe(q);
  });
});
