/**
 * One-time backfill: assign proper subcategories to auto-generated leads and their stubs.
 *
 * Targets:
 *   - IntelLead records with subsection === 'Auto-Generated' AND subcategory === ''
 *   - Their corresponding IntelligenceBrief records (stub or published) with subcategory === ''
 *   - The matching entries in seedLeads.js (patches the file in-place)
 *
 * Uses GPT-4o-mini to batch-assign subcategories per category.
 *
 * Usage:
 *   cd backend && node scripts/backfillAutoGeneratedSubcategories.js
 *
 * Safe to re-run: already-assigned entries are skipped.
 */

require('dotenv').config();
const mongoose = require('mongoose');
const fs = require('fs');
const path = require('path');

const IntelligenceBrief = require('../models/IntelligenceBrief');
const { SUBCATEGORIES } = IntelligenceBrief;
const IntelLead = require('../models/IntelLead');

const SEED_LEADS_PATH = path.join(__dirname, '../seeds/seedLeads.js');

// ── Helpers ──────────────────────────────────────────────────────────────────

async function openRouterChat(messages, model = 'openai/gpt-4o-mini', maxTokens = 2048) {
  const res = await fetch('https://openrouter.ai/api/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${process.env.OPENROUTER_KEY}`,
      'Content-Type': 'application/json',
      'HTTP-Referer': process.env.CLIENT_URL || 'http://localhost:5173',
      'X-Title': 'SkyWatch',
    },
    body: JSON.stringify({ model, messages, max_tokens: maxTokens }),
  });
  if (!res.ok) throw new Error(`OpenRouter ${res.status}: ${await res.text()}`);
  return res.json();
}

/**
 * Ask the AI to assign a subcategory to each lead entry for a given category.
 * Returns a Map of title → subcategory string.
 */
async function assignSubcategories(category, leads) {
  const validSubs = SUBCATEGORIES[category] ?? [];
  if (!validSubs.length) return new Map(); // category has no subcategories

  const prompt = `You are assigning subcategories to RAF/military intel brief entries.

Category: ${category}
Valid subcategories (you MUST pick one of these exactly, or return "" if genuinely none fits):
${validSubs.map(s => `  - "${s}"`).join('\n')}

Entries to classify (title + subtitle):
${leads.map((l, i) => `${i + 1}. "${l.title}" — ${l.subtitle || '(no subtitle)'}`).join('\n')}

Return ONLY valid JSON — no markdown, no extra text:
{
  "assignments": [
    { "title": "exact title", "subcategory": "chosen subcategory or empty string" }
  ]
}`;

  const raw = await openRouterChat([{ role: 'user', content: prompt }]);
  const content = raw.choices?.[0]?.message?.content ?? '{}';
  const cleaned = content.replace(/```json\n?|```/g, '').trim();
  const assignments = JSON.parse(cleaned).assignments ?? [];

  const result = new Map();
  for (const a of assignments) {
    if (a.title && validSubs.includes(a.subcategory)) {
      result.set(a.title, a.subcategory);
    }
  }
  return result;
}

/**
 * Patch a single `subcategory: ''` entry in seedLeads.js for a given title.
 * Replaces the first occurrence of the entry line that matches the title.
 */
function patchSeedLeadsEntry(src, title, subcategory) {
  // Match lines like: { title: 'Foo Bar', ..., subcategory: '', ... }
  // We escape the title for use in a regex
  const esc = s => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace(/'/g, "\\'");
  const titlePattern = esc(title);
  // Match a line containing this title and subcategory: ''
  const re = new RegExp(
    `(\\{[^}]*title:\\s*'${titlePattern}'[^}]*subcategory:\\s*)'(?:'[^}]*\\})`,
    's'
  );
  // Simpler approach: find the line, replace subcategory: '' with subcategory: 'VALUE'
  const lines = src.split('\n');
  const escapedSub = subcategory.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  let patched = false;
  const result = lines.map(line => {
    if (patched) return line;
    // Check if this line contains the exact title and an empty subcategory
    if (line.includes(`'${title}'`) && line.includes(`subcategory: ''`)) {
      patched = true;
      return line.replace(`subcategory: ''`, `subcategory: '${escapedSub}'`);
    }
    return line;
  });
  return { src: result.join('\n'), patched };
}

// ── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log('Connected to MongoDB');

  // 1 — find all auto-generated leads with empty subcategory
  const autoLeads = await IntelLead.find({
    subsection: 'Auto-Generated',
    $or: [{ subcategory: '' }, { subcategory: null }, { subcategory: { $exists: false } }],
  }).lean();

  if (!autoLeads.length) {
    console.log('No auto-generated leads with empty subcategory found. Nothing to do.');
    await mongoose.disconnect();
    return;
  }

  console.log(`Found ${autoLeads.length} auto-generated lead(s) with empty subcategory.`);

  // Group by category
  const byCategory = new Map();
  for (const lead of autoLeads) {
    if (!byCategory.has(lead.category)) byCategory.set(lead.category, []);
    byCategory.get(lead.category).push(lead);
  }

  const allAssignments = new Map(); // title → subcategory

  // 2 — AI-assign subcategories per category (batch of up to 30 at a time)
  for (const [category, leads] of byCategory) {
    const validSubs = SUBCATEGORIES[category] ?? [];
    if (!validSubs.length) {
      console.log(`[${category}] No subcategories defined — skipping ${leads.length} lead(s).`);
      continue;
    }

    console.log(`[${category}] Assigning subcategories for ${leads.length} lead(s)...`);
    const BATCH = 30;
    for (let i = 0; i < leads.length; i += BATCH) {
      const batch = leads.slice(i, i + BATCH);
      try {
        const map = await assignSubcategories(category, batch);
        for (const [title, sub] of map) allAssignments.set(title, sub);
        console.log(`  Batch ${Math.floor(i / BATCH) + 1}: assigned ${map.size}/${batch.length}`);
      } catch (err) {
        console.error(`  Batch ${Math.floor(i / BATCH) + 1} failed (non-fatal):`, err.message);
      }
    }
  }

  if (!allAssignments.size) {
    console.log('No assignments returned by AI. Exiting.');
    await mongoose.disconnect();
    return;
  }

  console.log(`\nAI returned ${allAssignments.size} assignment(s). Applying...`);

  // 3 — update IntelLead records
  let leadUpdated = 0;
  for (const [title, subcategory] of allAssignments) {
    const res = await IntelLead.updateOne({ title }, { $set: { subcategory } });
    if (res.modifiedCount) leadUpdated++;
  }
  console.log(`Updated ${leadUpdated} IntelLead record(s).`);

  // 4 — update stub/published IntelligenceBrief records with matching titles
  let briefUpdated = 0;
  for (const [title, subcategory] of allAssignments) {
    const res = await IntelligenceBrief.updateMany(
      { title, $or: [{ subcategory: '' }, { subcategory: null }, { subcategory: { $exists: false } }] },
      { $set: { subcategory } }
    );
    briefUpdated += res.modifiedCount;
  }
  console.log(`Updated ${briefUpdated} IntelligenceBrief record(s).`);

  // 5 — patch seedLeads.js
  let src = fs.readFileSync(SEED_LEADS_PATH, 'utf8');
  let seedPatched = 0;
  for (const [title, subcategory] of allAssignments) {
    const { src: newSrc, patched } = patchSeedLeadsEntry(src, title, subcategory);
    if (patched) {
      src = newSrc;
      seedPatched++;
    }
  }
  if (seedPatched) {
    fs.writeFileSync(SEED_LEADS_PATH, src, 'utf8');
    console.log(`Patched ${seedPatched} entry(ies) in seedLeads.js.`);
  } else {
    console.log('No seedLeads.js entries matched for patching (titles may use escaped characters — verify manually).');
  }

  console.log('\nBackfill complete.');
  await mongoose.disconnect();
}

main().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
